run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - errcheck
    - ineffassign
    - misspell
    - unparam
    - nakedret
    - prealloc
    - goimports
    - goconst
    - gocyclo
    - bodyclose
    - godot
    - thelper
    - predeclared
